# Enforces designate-mdns's `[service:mdns] listen` config on each host in
# `var.designate_mdns_listeners`. See `variables.tf`'s doc comment on that
# variable, and
# `../../pdns4-external-dns-rest-http-cr-shim/docs/specs/
# 2026-09-10-axfr-zone-transfer.md` for the root cause this closes out:
# `designate_pdns_pool.tf`'s pool config points AXFR clients (`pdns4-shim`)
# at this host, but until now nothing declared what designate-mdns itself
# actually listens on -- a manual `designate.conf` edit would work but
# would drift silently from what `dns_role_pool_configurations` expects.
#
# Idempotent by design, not just by Terraform's own diffing: the deployed
# script only rewrites `designate.conf` (and only then triggers the
# restart) when the file's current `listen` value doesn't already match --
# safe to re-run, and avoids restarting a live DNS service on every
# unrelated `tofu apply` that happens to touch this resource's dependency
# graph.
locals {
  designate_mdns_listen_values = {
    for host, config in var.designate_mdns_listeners : host => join(",", config.listen)
  }
}

resource "ssh_resource" "designate_mdns_listener" {
  for_each = var.designate_mdns_listeners

  host        = each.key
  user        = each.value.ssh_username
  agent       = true
  timeout     = "2m"
  retry_delay = "10s"

  file {
    destination = "/tmp/set_designate_mdns_listen_${each.key}.py"
    permissions = "0755"
    content     = <<-EOT
      #!/usr/bin/env python3
      # Generated by tofu-pcd's designate_mdns_listener.tf -- edits are
      # idempotent (see that file's comment) but will be overwritten by the
      # next `tofu apply` that touches this resource; change
      # `designate_mdns_listeners` in terraform.tfvars instead of editing
      # designate.conf directly.
      import re
      import sys

      PATH = "/opt/pf9/etc/pf9-designate/designate.conf"
      SECTION = "[service:mdns]"
      TARGET_LINE = "listen = ${local.designate_mdns_listen_values[each.key]}\n"

      with open(PATH) as f:
          lines = f.readlines()

      section_start = None
      section_end = len(lines)
      for i, line in enumerate(lines):
          if section_start is None and line.strip() == SECTION:
              section_start = i
              continue
          if section_start is not None and re.match(r"^\[[^]]+\]\s*$", line):
              section_end = i
              break

      if section_start is None:
          sys.exit(f"ERROR: {SECTION} section not found in {PATH}")

      listen_re = re.compile(r"^\s*listen\s*=")
      existing_idx = None
      for i in range(section_start + 1, section_end):
          if listen_re.match(lines[i]):
              existing_idx = i
              break

      changed = False
      if existing_idx is not None:
          if lines[existing_idx] != TARGET_LINE:
              lines[existing_idx] = TARGET_LINE
              changed = True
      else:
          lines.insert(section_start + 1, TARGET_LINE)
          changed = True

      if changed:
          with open(PATH, "w") as f:
              f.writelines(lines)
          print(f"{PATH}: {SECTION} listen set to {TARGET_LINE.strip()!r}; restarting designate-mdns")
      else:
          print(f"{PATH}: {SECTION} listen already {TARGET_LINE.strip()!r}; not restarting")

      # A sentinel line the commands step below greps for, rather than
      # trying to thread a Python exit code through `sudo` into a shell
      # conditional -- simpler than it sounds either way, but this keeps
      # the shell side to one line.
      print("CHANGED" if changed else "UNCHANGED")
    EOT
  }

  commands = [
    <<-EOT
      set -euo pipefail
      output=$(sudo python3 /tmp/set_designate_mdns_listen_${each.key}.py)
      echo "$output"
      if echo "$output" | grep -q "^CHANGED$"; then
        sudo systemctl restart pf9-designate-mdns
        echo "pf9-designate-mdns restarted"
      fi
    EOT
  ]
}
