[kvm_hosts]
mf-ms-a2-01.usmnblm01.rye.ninja

[kvm_hosts:vars]
ansible_user=automation-user
# ansible_ssh_private_key_file=~/.ssh/id_rsa

[pcd_vms]
pcd-ce ansible_host=fd97:45c2:b3a1:100::dead

[pcd_vms:vars]
ansible_user=ubuntu
